/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./index.html",
    "./Jogos/**/*.html",
    "./Vps/**/*.html",
    "./Wiki/**/*.{html,js}",
    "./Admin/**/*.{html,js}",
    "./Parceiros/**/*.html",
    "./*.js"
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#c2c6d6",
        "tertiary-container": "#31a634",
        "secondary-container": "#9e0038",
        "inverse-primary": "#005ac2",
        surface: "#11131a",
        "inverse-on-surface": "#2e3038",
        "primary-container": "#4d8eff",
        "on-primary": "#002e6a",
        "secondary-fixed-dim": "#ffb2bb",
        "surface-container-lowest": "#0c0e15",
        "secondary-fixed": "#ffd9dd",
        "outline-variant": "#424754",
        "surface-container-high": "#282a31",
        "inverse-surface": "#e2e2ec",
        "primary-fixed": "#d8e2ff",
        "on-tertiary-fixed": "#002202",
        "on-secondary-fixed-variant": "#910033",
        "surface-container": "#1d1f27",
        "on-tertiary-container": "#003204",
        tertiary: "#6cdf65",
        "on-tertiary": "#003a06",
        "on-error-container": "#ffdad6",
        "surface-container-low": "#191b23",
        "on-tertiary-fixed-variant": "#00530c",
        error: "#ffb4ab",
        "primary-fixed-dim": "#adc6ff",
        secondary: "#ffb2bb",
        "on-secondary-fixed": "#400012",
        "surface-variant": "#33343c",
        "error-container": "#93000a",
        outline: "#8c909f",
        "on-primary-fixed": "#001a42",
        "surface-tint": "#adc6ff",
        "on-primary-container": "#00285d",
        "on-primary-fixed-variant": "#004395",
        "on-background": "#e2e2ec",
        "surface-bright": "#373941",
        background: "#11131a",
        "on-secondary": "#670022",
        "surface-dim": "#11131a",
        "tertiary-fixed-dim": "#6cdf65",
        "on-surface": "#e2e2ec",
        "on-secondary-container": "#ffa7b2",
        "tertiary-fixed": "#88fc7e",
        "surface-container-highest": "#33343c",
        "on-error": "#690005",
        primary: "#adc6ff",
      },
      fontFamily: {
        headline: ["Plus Jakarta Sans", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}